# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0002_auto_20150611_1109")]

    operations = [
        migrations.AddField(
            model_name="courseoutline",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Section",
            ),
        ),
        migrations.AlterField(
            model_name="courseoutline",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Course",
            ),
        ),
        migrations.AlterField(
            model_name="courseoutline",
            name="term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Semester",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.SmallIntegerField(default=2016),
        ),
    ]
