# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:12
#######################
from __future__ import print_function, unicode_literals

from django.db import migrations

#######################


def forward_courseoutline_section(apps, schema_editor):
    """
    Data migration to set the section fk from the course/term fks
    """
    # historic course outline and section models -- not imported
    CourseOutline = apps.get_model("classes", "CourseOutline")
    Section = apps.get_model("classes", "Section")
    for outline in CourseOutline.objects.all():
        if outline.section is not None:
            continue
        section_list = Section.objects.filter(course=outline.course, term=outline.term)
        if section_list:
            outline.section = section_list[0]
            outline.save()
        else:
            print(
                "WARNING: Could not find a section for",
                outline.course.pk,
                outline.term.pk,
            )
            print("Assume this was a cancelled course... deleting outline")
            outline.delete()


def reverse_courseoutline_section(apps, schema_editor):
    """
    In reverse.
    """
    CourseOutline = apps.get_model("classes", "CourseOutline")
    for outline in CourseOutline.objects.all():
        save = False
        if outline.section and not outline.course:
            outline.course = outline.section.course
            save = True
        if outline.section and not outline.term:
            outline.term = outline.section.term
            save = True
        if save:
            outline.save()


class Migration(migrations.Migration):

    dependencies = [("classes", "0003_auto_20160112_0911")]

    operations = [
        migrations.RunPython(
            forward_courseoutline_section, reverse_courseoutline_section
        )
    ]
