# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("classes", "0006_auto_20160112_1127")]

    operations = [
        migrations.RenameModel(old_name="CourseOutline", new_name="SectionHandout")
    ]
