# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0008_auto_20160418_1420")]

    operations = [
        migrations.AlterModelOptions(
            name="sectionhandout",
            options={"ordering": ["section", "ordering", "label"]},
        ),
        migrations.AddField(
            model_name="sectionhandout",
            name="ordering",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
