# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 15:14
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0009_auto_20160419_0952")]

    operations = [
        migrations.CreateModel(
            name="CourseHandout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to remove this item without actually deleting it.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="course content",
                        help_text="Use lower case",
                        max_length=128,
                    ),
                ),
                ("ordering", models.PositiveSmallIntegerField(default=10)),
                ("path", models.FileField(upload_to="outlines/%Y/%m")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="classes.Course"
                    ),
                ),
            ],
            options={"ordering": ["course", "ordering", "label"]},
        )
    ]
