# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0010_coursehandout")]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    (b"00", b"Unknown"),
                    (b"cl", b"Lecture"),
                    (b"lb", b"Lab"),
                    (b"on", b"Online"),
                    (b"zz", b"Other"),
                ],
                default="00",
                max_length=2,
            ),
        )
    ]
