# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0011_section_section_type")]

    operations = [
        migrations.AlterField(
            model_name="coursehandout",
            name="path",
            field=models.FileField(upload_to="handouts/%Y/%m"),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    (b"00", b"Unknown"),
                    (b"cl", b"Lecture"),
                    (b"lb", b"Lab"),
                    (b"on", b"Online"),
                    (b"fw", b"Field work"),
                    (b"zz", b"Other"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="path",
            field=models.FileField(upload_to="handouts/%Y/%m"),
        ),
    ]
