# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0014_auto_20170602_1054")]

    operations = [
        migrations.AlterField(
            model_name="sectionschedule",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.Section"
            ),
        )
    ]
