# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0015_auto_20170607_0906")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="course",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                help_text="A url fragment which identies this course", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="coursehandout",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="coursehandout",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="coursehandout",
            name="label",
            field=models.CharField(
                default="course content", help_text="Use lower case", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="coursehandout",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="advertised",
            field=models.BooleanField(
                default=True,
                help_text="A department should be advertised if you are authoritive for it",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(
                help_text="A short character sequence which is used to construct course names, e.g., BIOL or GRAD",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="department",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Verbose name of the department, e.g., 'Biology' or 'Graduate Studies'",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="If a department is public, then it's course pages are available",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(
                help_text="A url which identifies the department", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="registration",
            field=models.IntegerField(verbose_name="Actual registration"),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="date",
            field=models.DateField(
                help_text='See <a href="http://umanitoba.ca/calendar">the UofM calendar / Academic Schedule</a>, <a href="http://umanitoba.ca/student/records/deadlines/">student records</a> and and <a href="http://umanitoba.ca/summer">Summer Session / Important Dates</a> for dates.'
            ),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Specify the end date for things like reading week, which last for more than one day.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importantdate",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="scheduletype",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="scheduletype",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="scheduletype",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="section",
            name="crn",
            field=models.CharField(max_length=10, verbose_name="CRN"),
        ),
        migrations.AlterField(
            model_name="section",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Additional section information or details, e.g., for topics courses",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="override_instructor",
            field=models.BooleanField(
                default=False,
                help_text="If this is set, then the instructor will not be changed by any automatic update",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("00", "Unknown"),
                    ("cl", "Lecture"),
                    ("cc", "Challenge for credit"),
                    ("lb", "Lab"),
                    ("on", "Online"),
                    ("fw", "Field work"),
                    ("zz", "Other"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="slug",
            field=models.SlugField(
                help_text="A url fragment which identies this section", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="label",
            field=models.CharField(
                default="syllabus", help_text="Use lower case", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="override_instructor",
            field=models.BooleanField(
                default=False,
                help_text="If this is set, then the instructor will not be changed by any automatic update",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="override_room",
            field=models.BooleanField(
                default=False,
                help_text="If this is set, then the room will not be changed by any automatic update",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="advertised",
            field=models.BooleanField(
                default=False,
                help_text="A semester should be advertised if relevant information should be displayed.",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="semester",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="slug",
            field=models.SlugField(
                help_text="A url fragment which identifies this semester", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="term",
            field=models.CharField(
                choices=[("1", "Winter"), ("2", "Summer"), ("3", "Fall")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="finish",
            field=models.DateField(help_text="Last day of classes."),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="start",
            field=models.DateField(
                help_text='First day of classes.  See <a href="http://umanitoba.ca/calendar">the UofM calendar / Academic Schedule</a> for dates.'
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this to remove this item without actually deleting it.",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.CharField(
                help_text='This should be a substring of "MTWRF".', max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
    ]
