# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0016_auto_20171017_1347")]

    operations = [
        migrations.AddField(
            model_name="section",
            name="additional_instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                related_name="additional_instructor_section",
                to="people.Person",
            ),
        ),
        migrations.AddField(
            model_name="sectionschedule",
            name="additional_instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                related_name="additional_instructor_sectionschedule",
                to="people.Person",
            ),
        ),
    ]
