# Generated by Django 2.0.1 on 2018-01-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0017_auto_20171108_1415")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Department",
            ),
        ),
        migrations.AlterField(
            model_name="coursehandout",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={
                    "active": True,
                    "department__active": True,
                    "department__advertised": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="additional_instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "instructor"},
                related_name="additional_instructor_section",
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Course",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "instructor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="term",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "advertised": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Semester",
            ),
        ),
        migrations.AlterField(
            model_name="sectionhandout",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={
                    "active": True,
                    "course__active": True,
                    "course__department__active": True,
                    "course__department__advertised": True,
                },
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Section",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="additional_instructors",
            field=models.ManyToManyField(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "instructor"},
                related_name="additional_instructor_sectionschedule",
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                help_text='Only people with the "instructor" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "instructor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="room",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="places.ClassRoom",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="section",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Section",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="timeslot",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="sectionschedule",
            name="type",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.ScheduleType",
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.SmallIntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name="semesterdaterange",
            name="semester",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "advertised": True},
                on_delete=django.db.models.deletion.PROTECT,
                to="classes.Semester",
            ),
        ),
    ]
