# Generated by Django 2.0.1 on 2018-01-30 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0018_auto_20180130_1424")]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="scheduled",
            field=models.BooleanField(default=False, verbose_name="Use for scheduling"),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="day",
            field=models.CharField(
                help_text='This should be a substring of "MTWRF".',
                max_length=16,
                validators=[django.core.validators.RegexValidator(regex="M?T?W?R?F?")],
            ),
        ),
    ]
