# Generated by Django 2.1.4 on 2018-12-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0020_auto_20180201_1022")]

    operations = [
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to remove this item without actually deleting it.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("equiv_group", models.SmallIntegerField(default=1)),
                ("minimum_grade", models.CharField(blank=True, max_length=64)),
                ("preferred", models.BooleanField()),
                ("corequisite", models.BooleanField()),
                ("optional", models.BooleanField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="classes.Course"
                    ),
                ),
            ],
            options={
                "ordering": ("equiv_group", "-preferred", "requisite"),
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Requisite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck this to remove this item without actually deleting it.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "outside_course",
                    models.CharField(
                        blank=True,
                        help_text="A description for an external requisite",
                        max_length=128,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="A link to the requisite (optional)"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Additional information for this requisite",
                        max_length=128,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="A local course",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.Course",
                    ),
                ),
            ],
            options={
                "ordering": ("outside_course", "course"),
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("00", "Unknown"),
                    ("cl", "Lecture"),
                    ("lb", "Lab"),
                    ("on", "Online"),
                    ("fw", "Field work"),
                    ("zz", "Other"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="requisite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="classes.Requisite"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisite", unique_together={("course", "outside_course")}
        ),
    ]
