# Generated by Django 2.1.4 on 2018-12-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0021_auto_20181206_1418")]

    operations = [
        migrations.AddField(
            model_name="requisite",
            name="rank",
            field=models.SmallIntegerField(
                default=None,
                help_text="Same rank items will be logically grouped where appropriate",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prerequisite",
            name="requisite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classes.Requisite"
            ),
        ),
    ]
