# Generated by Django 2.1.5 on 2019-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0022_auto_20181207_1459")]

    operations = [
        migrations.AlterField(
            model_name="requisite",
            name="rank",
            field=models.SmallIntegerField(
                blank=True,
                default=None,
                help_text="Same rank items will be logically grouped where appropriate",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="year",
            field=models.SmallIntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name="timeslot", name="name", field=models.CharField(max_length=64)
        ),
    ]
