# Generated by Django 2.2.1 on 2019-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("classes", "0023_auto_20190131_1159")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="detailed_program",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="coursehandout",
            name="public",
            field=models.BooleanField(
                choices=[(True, "Public"), (False, "Restricted")], default=True
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("00", "Unknown"),
                    ("cl", "Lecture"),
                    ("cc", "Challenge for credit"),
                    ("lb", "Lab"),
                    ("on", "Online"),
                    ("fw", "Field work"),
                    ("zz", "Other"),
                ],
                default="00",
                max_length=2,
            ),
        ),
    ]
